### ISSUE TITLE
Browser support request

### ISSUE THREAD

**Issue by ozer85** [evg4b/modern-json-formatter#22]
# Browser Support Request

Browser Details:
- Name: SigmaOS
- Version *(optional)*: 1.18.1.1
- Platform *(optional)*: MacOS Sequoia 15.1 (24B2082)

Additional Info:
- Link to the browser website: SigmaOS.com

**Comment by evg4b** [comment]
Hello @ozer85,
Thank you for being so interested in my extension.

I have some good news – the next version of the plugin will be compatible with the Sigma OS browser.

While the extension currently works flawlessly, and the planned future features are unlikely to change this, I want to inform you that this support is somewhat experimental. My plugin is primarily designed for Chrome-based browsers (Sigma OS is powered by WebKit), so I cannot fully guarantee the functionality of all future features in this browser.

Thank you for your understanding.

**Comment by evg4b** [comment]
@ozer85 Good news! A new version has been published in the app store.
Now you can try the extension in your favorite browser.

<p >
    <a href="https://chromewebstore.google.com/detail/modern-json-formatter/dmofgolehdakghahlgibeaodbahpfkpf">
        <img src="https://github.com/evg4b/modern-json-formatter/raw/main/.github/chrome-web-store.png" height="50px" alt="Available in the Chrome Web Store">
    </a>
    <a href="https://microsoftedge.microsoft.com/addons/detail/modern-json-formatter/edjgdbhdfdodmabofpnkngphlbpjpihj">
        <img src="https://github.com/evg4b/modern-json-formatter/raw/main/.github/microsoft-store.png" height="50px" alt="Available in Microsoft Store">
    </a>
</p>

**Comment by ozer85** [comment]
Thank you!
